version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5439:5432
    environment:
      POSTGRES_USER: zebrands
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: authorization